config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'groups#index'

  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end

  namespace :account do
    resources :groups
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  validates :title, :description, presence: true

  belongs_to :user
  has_many :posts

  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user 
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord

  belongs_to :group
  belongs_to :user 
end

app/models/post.rb
class Post < ApplicationRecord

  validates :content, presence: true
  belongs_to :group
  belongs_to :user

  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts

  has_many :group_relationships
  has_many :participated_groups, through: :group_relationships, source: :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController

  def index
      @groups = current_user.participated_groups 
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

  def index
    @posts = current_user.posts.recent
  end

  def edit
    @group = Group.find(params[:group_id])
    @post  = Post.find(params[:id])
    @post.group = @group
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :destroy, :update, :join, :quit]
  before_action :find_group_and_check_permission, only: [:update, :edit, :destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      @group.save
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  def show
    @group = Group.find(params[:id])
    @post = Post.new
    @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 9)
  end

  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "joined this group"
    else
      flash[:warning] = "You alread is groups member"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:danger] = "quit this group"
    else
      flashp[:warning] = "You are not this group member, can't quit"
    end

    redirect_to group_path(@group)
  end


  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])
    if current_user != @group.user
      redirect_to root_path, alert: "you have no permission"
    end
  end

  def group_params
    params.require(:group).permit(:title, :description)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)

    @post.group = @group
    @post.user = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @post  = Post.find(params[:id])
    @post.group = @group
  end

  def update
    @group = Group.find(params[:group_id])
    @post  = Post.find(params[:id])
    @post.group = @group

    if @post.update(post_params)
      redirect_to account_posts_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @post  = Post.find(params[:id])
    @post.group = @group

    @post.destroy
    redirect_to account_posts_path, alert: "Deleted #{@post.content}"
  end



  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    flash[:notice] = "welcome"
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key, value|%>
  <div class="alert alert-dismissable alert-<%= flash_class(key)%>">
    <button class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">

  <p class="text-center">Copyright ©2017 Rails 101
    <br>Design by xxx 
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Rails 101</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("signup", new_user_registration_path)%></li>
          <li><%= link_to("login", new_user_session_path)%></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email%>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("My Groups", account_groups_path)%></li>
              <li><%= link_to("My Posts", account_posts_path)%></li>
              <li><%= link_to("quit", destroy_user_session_path, method: :delete)%></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/groups/_from.html.erb
<%= simple_form_for @group do |f|%>
  <div class="form-group">
    <%= f.input :title, input_html: {class: "form-control"}%>
    <%= f.input :description, input_html: {class: "form-control"}%>
    <%= f.submit "submit", class: "btn btn-primary", data: { disable_with: "submitting...."}%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <h1>Edit</h1>
  <%= render "from"%>

app/views/groups/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to("new group",new_group_path, class: "btn btn-default")%>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>title</th>
        <th>description</th>
        <th colspan="3">user</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group|%>
        <tr>
          <td>#</td>
          <td><%= link_to group.title, group%></td>
          <td><%= render_group_description(group)%></td>
          <td><%= group.user.email%></td>
          <td>
            <% if current_user && current_user == group.user%>
              <%= link_to("Delete", group_path(group), method: :delete, class: "btn btn-default", data: {confirm: "are you sure?"})%>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-default")%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>
<hr>
<%= render "from"%>

app/views/groups/show.html.erb
<div class="container text-center">
  <h1><%= @group.title%></h1>

  <p><%= @group.description%></p>
</div>
<div class="container">
  <div class="pull-right">
    <% if current_user && current_user.is_member_of?(@group)%>
      <label class="label label-success">Groups</label>
      <%= link_to("Quit Group", quit_group_path(@group),method: :post, class: "btn btn-default")%>
    <% else %>
      <label  class="label label-danger">stranger</label>
      <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-default")%>
    <% end %>
  </div>
  <table class="table table-hover">
    <% @posts.each do |post|%>
      <tr>
        <td><%= post.content%></td>
        <td><%= post.user.email%></td>
      </tr>
    <% end %>
  </table>
  <div class="text-center">
    <%= will_paginate @posts%>
  </div>
</div>
<div class="container">
  <% if current_user && current_user.is_member_of?(@group)%>
    <%= simple_form_for [@group,@post] do |f|%>
      <%= f.input :content%>
      <%= f.submit "submit", data: { disable_with: "submitting...."}%>
    <% end %>
  <% else %>
    <h1 class="text-center">Join this group and write a posts</h1>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails102</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar"%>
      <%= render "common/flashes"%>
      <%= yield %>
    </div>

    <%= render "common/footer"%>
  </body>
</html>

app/views/posts/edit.html.erb
<%= simple_form_for [@group, @post] do |f|%>
  <%= f.input :content%>
  <%= f.submit "submit", data: { disable_with: "submitting..."}%>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <%= simple_form_for [@group,@post] do |f|%>
    <%= f.input :content%>
    <%= f.submit "submit", data: { disable_with: "submitting...."}%>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>welcome</h1>